// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "swapi-aws-sls",
    "version": "1"
  },
  "paths": {
    "/": {
      "get": {
        "summary": "api",
        "description": "",
        "operationId": "api.get./",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/getJediTranslate": {
      "get": {
        "summary": "getJediTranslate",
        "description": "",
        "operationId": "getJediTranslate.get./getJediTranslate",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/crearJedi": {
      "post": {
        "summary": "createJedi",
        "description": "",
        "operationId": "createJedi.post./crearJedi",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/obtenerJedis": {
      "get": {
        "summary": "getJedis",
        "description": "",
        "operationId": "getJedis.get./obtenerJedis",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};